server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  profiles:
    active: development
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.mysql.dialect.MySQL5InnoDBDialect
    generate-ddl: true
